import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import StatusBadge from "./StatusBadge";
import { format } from "date-fns";
import { Repeat } from "lucide-react";
import { getRecurrencePatternLabel } from "@/lib/recurringUtils";
import { useTranslation } from "@/i18n";

type TaskStatus = "pending" | "in_progress" | "completed";
type TaskType = "one-time" | "recurring";
type RecurrencePattern = "none" | "weekly" | "monthly" | "quarterly" | "semi-annual" | "yearly";

interface TaskCardProps {
  taskId: string;
  description: string;
  clientName: string;
  status: TaskStatus;
  createdAt: Date;
  taskType?: TaskType;
  recurrencePattern?: RecurrencePattern;
  recurrenceInterval?: number;
  isAutoGenerated?: boolean;
  onClick?: () => void;
}

export default function TaskCard({
  taskId,
  description,
  clientName,
  status,
  createdAt,
  taskType = "one-time",
  recurrencePattern = "none",
  recurrenceInterval = 1,
  isAutoGenerated = false,
  onClick,
}: TaskCardProps) {
  const t = useTranslation();
  const isRecurring = taskType === "recurring";
  
  return (
    <Card
      className={`p-5 hover-elevate active-elevate-2 cursor-pointer overflow-visible ${
        isRecurring ? "border-l-4 border-l-primary" : ""
      }`}
      onClick={onClick}
      data-testid={`card-task-${taskId}`}
    >
      <div className="flex items-start justify-between gap-4 mb-3">
        <div className="flex items-center gap-2 flex-1">
          {isRecurring && <Repeat className="w-4 h-4 text-primary" />}
          <h3 className="text-lg font-medium flex-1" data-testid={`text-task-description-${taskId}`}>
            {description}
          </h3>
        </div>
        <StatusBadge status={status} />
      </div>
      
      <div className="flex items-center gap-2 text-sm text-muted-foreground mb-2">
        <span data-testid={`text-client-name-${taskId}`}>{clientName}</span>
        <span>•</span>
        <span className="text-xs" data-testid={`text-created-date-${taskId}`}>
          {format(createdAt, "MMM d, yyyy")}
        </span>
      </div>

      {isRecurring && (
        <div className="flex items-center gap-2 mt-3">
          <Badge variant="secondary" className="text-xs" data-testid={`badge-recurrence-${taskId}`}>
            {getRecurrencePatternLabel(recurrencePattern, recurrenceInterval || 1)}
          </Badge>
          {isAutoGenerated && (
            <Badge variant="outline" className="text-xs" data-testid={`badge-auto-generated-${taskId}`}>
              {t.tasks.autoGenerated}
            </Badge>
          )}
        </div>
      )}
    </Card>
  );
}
